version: '3.8'

services:
  excalidraw:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for dev
      args:
        NODE_ENV: development
    container_name: excalidraw-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    command: ["yarn", "start"]

networks:
  default:
    driver: bridge
